[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd ../frontend && npm run build",
  "mkdir -p ../backend/public",
  "cp -r ../frontend/dist/* ../backend/public/"
]

[start]
cmd = "cd backend && npm start" 